repos:
  - repo: local
    hooks:
      - id: clang-format-check
        name: Check formatting with clang-format (dry-run)
        # note: has to use clang version 15
        entry: bash -c 'find app drv mari \( -name "*.c" -o -name "*.h" \) -exec clang-format --dry-run --Werror {} +'
        language: system
        pass_filenames: false
      - id: gateway-network-id-check
        name: "Ensure gateway uses MARI_NET_ID_DEFAULT "
        entry: grep MARI_NET_ID_DEFAULT app/03app_gateway_net/main.c
        language: system
        pass_filenames: false
      - id: node-network-id-check
        name: "Ensure node uses MARI_NET_ID_DEFAULT "
        entry: grep MARI_NET_ID_DEFAULT app/03app_node/main.c
        language: system
        pass_filenames: false
